name: TIP MSG Email Alert

on:
  schedule:
    - cron: '0 */2 * * *'  # 매 2시간마다 실행
  workflow_dispatch:

jobs:
  run-email-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas

      - name: Run TIP alert bot
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: |
          python tip_alert_bot.py
